name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  Deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the repository
        run: npm run build

      - name: Stop running application
        run: pm2 delete server-dashboard || true

      - name: Start the application
        env:
          API_URL: ${{ secrets.API_URL }}
          FILEPATH: ${{ secrets.FILEPATH }}
          NEXT_URL: ${{ secrets.NEXT_URL }}
        run: pm2 start npm --name=server-dashboard -- start
